### ISSUE TITLE
public JSONObject(Object bean) null check

### ISSUE THREAD

**Issue by looly** [stleary/JSON-java#204]
`public JSONObject(Object bean)` method not has `null` checker.

**Comment by stleary** [comment]
@looly there is a unit test for that. See https://github.com/stleary/JSON-Java-unit-test  > JSONObjectTest.java > jsonObjectByNullBean(). I think throwing an exception is the right behavior. However, some improvements might be in order:
* Throw a JSONException with explanatory text, rather than a generic NPE
* Add a @throws description to the JavaDoc
* Add a throws declaration to the method signature

Will that work for you?
There may be other methods in the project which would benefit from these changes as well.

Any opinions on throwing a more specific type of exception, or on whether an exception should be thrown at all?

**Comment by looly** [comment]
I know, thank u~

**Comment by stleary** [comment]
After some thought, prefer not to change the thrown exception. If you want to submit a pull request to update the JSONObject(bean) method comments, please proceed.
