### ISSUE TITLE
Implement the javax.json interfaces?

### ISSUE THREAD

**Issue by alexsdutton** [stleary/JSON-java#209]
Would you be interested in me doing the work to have org.json implement the [javax.json interfaces](https://docs.oracle.com/javaee/7/api/javax/json/package-summary.html)? This should help with improving compatibility between JSON libraries (and would be a first step towards making [json-schema](https://github.com/everit-org/json-schema) work with javax.json as well as org.json.

**Comment by johnjaylward** [comment]
While it makes sense to implement the common interface, at first glance I can see some items already that would cause incompatibilities with existing applications that use JSON-Java. The first being that JSON-Java does not have a common JsonValue type that all the other types inherit. We would have to modify the existing type interfaces to reflect that.

We've had previous discussions on this ( #153 ), but at the time we did not want to enforce a String key like the current javax.json.JsonObject wants to enforce.

I do think it would be healthy for this project if we go back and reconsider those constraints in order to implement this. However, it also looks like this would force us back to a Java7 dependency instead of Java6.

I believe we should use this issue as a discussion of whether the majority of users think this would benefit them overall, or if they prefer the current interface.

**Comment by johnjaylward** [comment]
Also, I just noticed this would also add a dependency outside of json-java itself, which is currently frowned on. I had thought this was in the rt.jar at first, but it is actually separate. Some people may not want the extra memory/disk space that takes up in their releases, especially for mobile and embedded systems.

**Comment by stleary** [comment]
Sorry for not commenting sooner, was caught up in yet another end of sprint. @alexsdutton, by all means proceed with an implementation. You will need to address in some form the issues that @johnjaylward brought up.

**Comment by stleary** [comment]
Closed pending a possible future pull request.
