### ISSUE TITLE
[Question] Where can I find a jar version of this?

### ISSUE THREAD

**Issue by Arinerron** [stleary/JSON-java#211]
I found no legitimate jar versions of this library, and there are none in this repository. Any ideas for where I could download one? (compiling didn't work, and I prefer an official release rather than my compiled copy anyways.)

Thanks!

**Comment by stleary** [comment]
Here is a jar of the latest release (2 Feb 2016): https://search.maven.org/remotecontent?filepath=org/json/json/20160212/json-20160212.jar

We don't keep jars with the project since GitHub does not natively support that. The maven releases are frequent enough that you can always download a more or less current jar from there.

**Comment by Arinerron** [comment]
Thanks a ton! By the way, I suggest documenting the URL (I saw a bunch of posts on the internet with the same question).

**Comment by johnjaylward** [comment]
it's in the README file on the front page of this repo

**Comment by Arinerron** [comment]
I didn't even see that when I was looking in file :stuck_out_tongue_winking_eye: Thank you!
