### ISSUE TITLE
Issue with value only json

### ISSUE THREAD

**Issue by supersloth** [stleary/JSON-java#238]
According to RFC7159 http://www.ietf.org/rfc/rfc7159.txt a json object that is only a string, a number, or a boolean is valid (see start of page 12 on link)

>    Here are three small JSON texts containing only values:
> 
>    "Hello world!"
> 
>    42
> 
>    true

however when calling jsonObject the following error is thrown 
`Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]`

that is with me calling 
`JSONObject jsonObj = new JSONObject("Hello world!");`

it seems to work with number as number
`JSONObject jsonObj = new JSONObject(42);`
but not number presented as string
`JSONObject jsonObj = new JSONObject("42");`

the same is true of 
```
JSONObject jsonObj = new JSONObject(true);
JSONObject jsonObj = new JSONObject("true");
```

is there an issue when parsing the strings? or am i doing it incorrectly? this problem arose because i am reading the contents of a file, into a string, then sending the built string of information to the JSONObject. 
this means
`"Hello World!"` never works, but it also means 
`42` never works, because after it is read in from the file, it becomes `"42"`, and it breaks since it now sees it as a string.

**Comment by johnjaylward** [comment]
This implementation does not conform to that RFC. Also, the section you are referring to call that json text, but you are trying to use a json object.

**Comment by supersloth** [comment]
oh really? the wiki page points out that RFC specifically: https://github.com/stleary/JSON-java/wiki I am not sure what you mean on the second part.

**Comment by johnjaylward** [comment]
Read all of section 13 - pages 11&12. You are trying to parse generic "json text" with a "json object".

You may want to try using the JSONTokener class instead. It's probably over to what you want.

**Comment by stleary** [comment]
@supersloth thanks for the suggestion. Do you have a use case, or is this a concern about being in compliance with the spec? If there is a use case, what exactly are you asking for?

**Comment by supersloth** [comment]
@stleary thanks for getting back to me. well luckily my use case is more academic so i'm not relying on it to push anything today. but the problem i'm trying to solve follows json spec to mean that both

```
{
    "days" : 365
}
```
as the contents of `file1.json`
and 
`-5`
as the contents of `file2.json` 
are both valid json inputs for processing. the first case works GREAT! the second is where it errors out. i thought since by definition in the RFC it meet this standard in the docs

> Construct a JSONObject from a source JSON text string. This is the most commonly used JSONObject constructor.

it would work, but i see now in the docs it specifies the braces as input:

> Parameters:
> source A string beginning with { (left brace) and ending with }  (right brace).
> Throws:
> JSONException - If there is a syntax error in the source string or a duplicated key.

so maybe i'm just SOL.

**Comment by stleary** [comment]
As I understand it, when the lib parses a boolean or number, it is actually parsing the autoboxed object as a bean. For example:
````
JSONObject jsonObject = new JSONObject(true);
// calls this ctor
public JSONObject(Object bean);
````
The boolean value true is autoboxed by the compiler into a Boolean, which matches the JSONObject (Object bean) constructor. The JSONObect(bean) constructor populates the JSONObject with the object's public getters. Since Boolean has none, the JSONObject remains emtpy. You get the same result with integers, which autobox to Integer. Strings don't autobox to anything, so they go through the JSONObject(String) constructor, which expects JSON object text, starting with {.

If your entire document consists of a simple string, a number, or a boolean, than RFC7159 would consider that valid JSON. Suppose we had a JSONText class which would parse valid JSON text, and you initialized some instances with new JSONText("hello world"), new JSONText(42), and new JSONText(true).  Then what useful functionality could the library provide for those JSONText objects?

**Comment by johnjaylward** [comment]
@stleary, I think to be able to fully parse a JSON Text as mentioned in the RFC we'd need to create a base ```JSONValue``` interface and have both ```JSONObject``` and ```JSONArray``` implement it. We would also need to create new implementations of ```JSONValue``` for Strings, Numbers, Boolean, and Null (like mentioned in #163)

Then we would have a generic parser that could parse a JSON Text and return a ```JSONValue``` which could be an instance of any of the above.

```java
JSONValue jv1 = JSONParser.parse("null");
JSONValue jv2 = JSONParser.parse("{\"key\":\"value\"}");

assert jv1 == JSONValue.NULL : "jv1 should be JSONValue.NULL";
assert jv2 instanceof JSONObject != null: "jv2 should be a JSONObject";
```

```jv1``` would evaluate to the instance of JSONValue.NULL and ```jv2``` would evaluate to an instance of JSONObject.

If we didn't want to go the whole ```JSONValue``` route, then just having a simple parser that read a JSON Text and returned an ```Object``` would probably work as well. This could probably fit in with the current ```JSONTokener```

```java
Object jv1 = JSONParser.parse("null");
Object jv2 = JSONParser.parse("{\"key\":\"value\"}");

assert JSONObject.NULL.equals(jv1) : "jv1 should be JSONObject.NULL";
assert jv2 instanceof JSONObject : "jv2 should be a JSONObject";
```

The ```Object``` way makes the caller try a little harder to figure out what type of JSON data was read, but would require less overhall in the library itself.

I don't think it would make sense to have ```JSONText``` be a full object like ```JSONArray``` or ```JSONObject```. I think the implementation of that would be clunky as you mention and it would be hard to have a real use-case.

or... maybe I'm overthinking this since it's almost 2am and I need probably sleep.

The only reason I can see any of this being needed is if for some reason you wouldn't know what your input is. However, since JSON is supposed to be a data interchange format, I find that an actual use-case of not knowing your data would be hard to come by. Or maybe people are using JSON for some really random stuff these days.

**Comment by johnjaylward** [comment]
I was overthinking it...

We can currently do this:

```java
JSONTokener jt = new JSONTokener("\"some input string\"");
Object val = jt.nextValue();

assert val instanceof String : "val should be a string";
assert "some input string".equals(val) : "val is not the expected value;
```

That will solve the existing issue.

**Comment by stleary** [comment]
@johnjaylward thanks for the thorough analysis. I will take a look at the actual code using JSONTokener, to see how much of this is already supported in some form or other.

**Comment by stleary** [comment]
@johnjaylward  you were right, JSONTokener already does pretty much what is needed. For example, given this code fragment:
````
        StringReader stringReader = new StringReader("Hello world\nhi\n42\n42\ntrue\nfalse\nnull\n3e5\n-25");
        JSONTokener jsonTokener = new JSONTokener(stringReader);
        while (jsonTokener.nextClean() != 0) {
            jsonTokener.back();
            Object obj = jsonTokener.nextValue();
            String s = obj.toString();
            System.out.println(obj.getClass()+" : "+s);
        }
````
The output is:
class java.lang.String : Hello world
class java.lang.String : hi
class java.lang.Integer : 42
class java.lang.Integer : 42
class java.lang.Boolean : true
class java.lang.Boolean : false
class org.json.JSONObject$Null : null
class java.lang.Double : 300000.0
class java.lang.Integer : -25

The only trick here is that no JSON spec defines a separator for texts, and it would not be great design to build a new tokener for each text. However, JSONTokener does return on chars less than space, so any of the ASCII control chars should work. So in the example above, I have chosen to use linefeeds as the separator. I think this provides adequate support for JSON text. Let me know if anyone disagrees, otherwise I think I can close this issue.
