### ISSUE TITLE
JSONObject::quote().  Why special case for "</" but not "/"

### ISSUE THREAD

**Issue by budric** [stleary/JSON-java#26]
Hi,
I'm having trouble understanding this code:
case '/':
                if (b == '<') {
                    sb.append('\');
                }
                sb.append(c);
                break;

Why is escape character '\' only appended when the previous character is <.  Looking at JSON control characters, the '/' is always a control character and should be prefixed with \.  Yet the code doesn't do that.

Thanks,

**Comment by Doogiemuc** [comment]
No he is right. JsonObject DOES quote forward slashes  in `JsonStringer.string(String value)` method.

**Comment by johnjaylward** [comment]
@Doogiemuc the forward slash escape is technically optional in the JSON spec, which is what Douglas was talking about. The reason that this library escapes them is because embedding JSON directly into HTML can cause "remote code execution" issues when you don't escape them. We escape them by default for safety, not because it's required by the spec.

For more information see: https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped#1580682
