### ISSUE TITLE
XML.toString() with key "content"

### ISSUE THREAD

**Issue by djoerd** [stleary/JSON-java#286]
The `XML.toString()` function seems to ignore keys when they are called "content", strange but true...(?) 

    import org.json.JSONObject;
    import org.json.XML;
    
    public class JSONbug {

        private static void test(String jsonString) {
            JSONObject json = new JSONObject(jsonString);
            System.out.print("Given the JSON object:");
            System.out.println(json);
            System.out.print("which has the keys: ");
            System.out.println(json.keySet());
            System.out.println("If we convert to XML, we get: ");
            System.out.println(XML.toString(json));
        }

        public static void main( String[] args ) {
            System.out.println("Test 1: If a JSON key is 'content', things break:");
            test("{\"content\": \"test this\", \"status\": \"error\"}");
            // test this<status>ok</status>
            System.out.println("-----------------");
            System.out.println("Test 2: keys like 'contents' work fine:");
            test("{\"contents\": \"test this\", \"status\": \"ok\"}");
            // <contents>test this</contents><status>ok</status>
        }
    }

**Comment by stleary** [comment]
XML/JSON transformations are somewhat broken, and probably cannot be fixed. However, it is reasonable to try to make the code work a little better. You can get some information about the use of the "content" keyword in https://github.com/stleary/JSON-Java-unit-test/blob/master/src/test/java/org/json/junit/XMLTest.java (search for "content"). 

Someone proposed making the keyword configurable in #108, but at the time it was not accepted. No objection to proposing a similar workaround now, except that it has to be done in a way that is both functionally correct, and does not break existing code.

**Comment by djoerd** [comment]
I see, thanks for the quick reply. What workaround do you recommend?

I receive JSON from an external source that I cannot control (which happened to use "content" one day), and need to produce XML output.  My guess is,  I need to replace all keys called "content" before transforming? There are no other "reserved keywords"?

Haven't studied the pull request you reference in detail, but a configurable "content" keyword would help.

**Comment by stleary** [comment]
Best practice is to do your own analysis. 

- Helps ensure the person doing the fix fully understands the issue
- Avoids the conflict of the code reviewer helping write the code
- The person who needs the fix will be able to best determine if it will work with their data

That being said, #108 seems like a reasonable approach, touching public methods toJSONObject() and toString(), and the private parse() method. Problem is that the API has changed since then. There is already an optional boolean parameter "keepStrings" to override parsing of boolean and numeric values. Adding another optional parameter makes the API even more kludgy. Also, any solution needs to work with Java 1.6, so new language features are not available for the fix.

Consider checking whether the JSONML class will do a better job for you.

**Comment by djoerd** [comment]
Thanks for the JSONML suggestion, but JSON-java does fine for now. Not sure what you mean by 'do your own analysis', but I guess I will end up with something like this:

    json = json.replaceAll("\"content\":", "\"my_org_json_content\":");
    xml  = XML.toString(new JSONObject(json));
    xml  = xml.replaceAll("my_org_json_content>", "content>");

**Comment by johnjaylward** [comment]
@djoerd see the new PR #412 . It should handle your usecase with a configurable "content" tag. Please try it out and let us know if it works for you
