### ISSUE TITLE
XML.toString does not handle the case where JSON keys are not valid XML element names.

### ISSUE THREAD

**Issue by imhogan** [stleary/JSON-java#294]
JSON key names are not as tightly constrained as XML element names - eg:
 {"6":"x"," this has spaces and quotes\"!":"Ouch"}
 is a valid JSON object, but XML.toString would convert this to 
<root><6>x</6>< this has spaces and quotes"!>Ouch"</ this has spaces and quotes"!></root>
Which is not valid XML. One solution is to prefix element names which start with a digit with _ and replace other invalid characters with an _ too. Whilst this makes the resultant XML valid, meaning can be lost, so to retain the meaning an attribute could be added to provide the original JSON key name. This approach would result in the XML:
<root><_6 JSON_Key="6">x</6><_this_has_spaces_and_quotes__ JSONKey=" this has spaces and quotes&quot;!">Ouch"</_this_has_spaces_and_quotes__></root>

See https://www.w3.org/TR/REC-xml/#NT-Name for constraints on XML element names. Note, ":" should be replaced with another character as otherwise it could result in an element name which appears to contain a namespace prefix.

**Comment by johnjaylward** [comment]
This has been brought up before in #166, #138, and #123. I don't see this getting corrected anytime soon.

It is currently expected that the developer calling this library pre-process the JSON to make any correction to key names so that it fits their application needs.

I doubt any change here would break an existing application since invalid node name could not be processed. I personally believe the best solution would be to throw an exception during XML generation if the node name would be invalid.

**Comment by stleary** [comment]
Changing users' content is not an option. In #123, Douglas offered throwing an exception on invalid input. No objection to someone doing this now.
