### ISSUE TITLE
[Feature] XML Schema aware XML -> JSON conversion

### ISSUE THREAD

**Issue by kringol** [stleary/JSON-java#302]
Support providing an xml schema (xsd) file/string to the XML2JSON transformer to avoid guessing if it should be String or Number or dealing with arrays.

**Comment by erosb** [comment]
Good idea, but it would be a huge effort, I'm afraid. Since this library is currently in maintenance mode, new features are discouraged in general. I don't think @stleary would agree in implementing it (not even if it arrives in the form of a PR).

You may consider developing a standalone library for this purpose.

**Comment by stleary** [comment]
Agreed, parsing xsd files is beyond the scope of the project, and we don't support incorporating 3rd party libraries (https://github.com/stleary/JSON-java/wiki/FAQ).
