### ISSUE TITLE
add map and list functionality in JSONObject/JSONArray

### ISSUE THREAD

**Issue by apolo92** [stleary/JSON-java#327]
implements in jsonObject Map funcions containsValue , containsKey , forEach  ,isEmpty...
implements in jsonArray List funcions contains ,  isEmpty, ....

And implements stream Java8 ? ¿

**Comment by stleary** [comment]
Just realized that Java versions are not addressed in the [FAQ](https://github.com/stleary/JSON-java/wiki/FAQ), so I added this text:

**What version of Java does this project require?**

At the present time Java 6 is required, in order to support Android devices. This is not a project 
requirement but we are going to try to support Android for as long as practical. That means
we cannot accept pull requests that require Java 7 or greater.

**Comment by stleary** [comment]
This issue should be addressed in the comments. Please add a note if you think it should be re-opened for any reason.
