### ISSUE TITLE
Name Sensitivity to word "Content" as the JSON property name

### ISSUE THREAD

**Issue by NavidHeydari** [stleary/JSON-java#344]
Hi Devs,
Appreciate your efforts so far.

it seems something is sensitive to word "content" inside my JSON since whenever I tried to use this name inside my json and call XML to convert that into XML, it will treat my data in an odd way, for example:

\"parent\": [
{
\"content\" : \"mydata\",
\"anotherProperty\" : 12
}, {
\"content\" : \"mydata1\",
\"anotherProperty\" : 13
}
]

it will generate something like this:

<parent>mydata<anotherProperty>12</anotherProperty></parent><parent>mydata1<anotherProperty>13</anotherProperty></parent>

I assume it should produce something like this:

<parent><content>mydata</content><anotherProperty>12</anotherProperty></parent>
<parent><content>mydata1</content><anotherProperty>13</anotherProperty></parent>

am I doing something wrong?
I should mention that my code is working fine with all the other properties, just it seems something is sensitive to content name. 

Thanks for your efforts,
Navid :)

**Comment by johnjaylward** [comment]
Yes, that is as-designed. the "content" tag is used to not CDATA sections of the XML

**Comment by stleary** [comment]
The XML transformations are understood to be problematic and imperfect. It is unfortunate that a common word like 'content' is used here, but no changes to this part of the XML code are anticipated, due to the likelihood that it would break existing applications. Maintaining backwards compatibility is one of the highest priorities for this project.
