### ISSUE TITLE
better number treatment in toString()?

### ISSUE THREAD

**Issue by mikeliucc** [stleary/JSON-java#367]
Hi,

JSONObject.java (as of https://github.com/stleary/JSON-java/commit/2e0a8137bd911736ded8bda32c07203a0a97e9a6), line 2259 - 2261 (`writeValue()`) looks like this:

     BigDecimal testNum = new BigDecimal(numberAsString);
     // Close enough to a JSON number that we will use it unquoted
     writer.write(numberAsString);

Would it be possible to change the code to use `testNum` as the argument of `writer.write()`, instead of `numberAsString`?

The method `writeValue()` is called indirectly by `toString()`, which create the stringified version of the JSON instance.  Using 

     writer.write(testNum.toString());     // line 2261

would produce more readable and pleasant output.  For example, instead of creating a String representation of JSON like this:

     {"number":1.2345678909E8, ...}

It would produce:

     {"number":123456789.09, ...}

Turns out that this looks much closer to the original JSON content as well (in our case).

Would you please consider this code change?  Thank you!

**Comment by johnjaylward** [comment]
While I agree that `123456789.09` is much more readable to a human than `1.2345678909E8`, I don't see us making this change:

1. Both are valid JSON representations, there is not reason from a specification standpoint to favor one over the other
2. The 'e' format may have better portability
3. JSON is not truly meant to be human readable except for possibly debugging purposes.

The last point is getting weaker by the year as people are moving to JSON config files which are meant to be maintained by hand. However, the first 2 are still quite valid today.

If we force the output to prevent 'e' notation, we may end up with longer representations that aren't supported by all platforms. i.e 0.00000000000000000000000000000112345849 would be forced as output instead of being simplified to 1.12345849e-30.

Adding in logic to detect when e notation is more acceptable than standard notation would be more than we want in this reference application.

**Comment by stleary** [comment]
Thanks for bringing up this issue. In order not to break existing applications, changes to JSON output are limited to bugs that are worse than the current behavior. For this reason, and for the reasons cited by @johnjaylward, no changes in numeric output are planned at this time. This is probably a case where forking the project would be a better solution.
