### ISSUE TITLE
numberToString shaves off trailing zeros

### ISSUE THREAD

**Issue by gaul** [stleary/JSON-java#369]
`numberToString` shaves off trailing zeros, which prevents JSON-java from correctly transforming part of my `pom.xml`:

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.20</version>
      </plugin>
```

I get the incorrect:

```json
              "plugin": {
                "groupId": "org.apache.maven.plugins",
                "artifactId": "maven-surefire-plugin",
                "version": 2.2
              }
```

Will you accept a pull request to remove this behavior or add a configuration to control it?

**Comment by johnjaylward** [comment]
The xml parser has an option to read all calues as strings, which will prevent this behavior.

**Comment by gaul** [comment]
Calling `XML.toJSONObject(String string, boolean keepStrings)` with `keepStrings` true works around this issue for me.  Thanks for the pointer @johnjaylward!

Before closing this, do other parsers perform this 2.20 -> 2.2 canonicalization by default?

**Comment by johnjaylward** [comment]
The issue is that the xml parser tries to guess values. Initially it converted the string "2.20" to the number (double) 2.2. The json output tries to use as few bytes as possible, so any numbers it outputs get trimmed of trailing zeros.

I believe other parsers would perform the same trimming of actual numbers. String values should be left alone.

**Comment by gaul** [comment]
Most JSON exporters usually know the types of variables but JSON-java only sees strings coming from the XML input.  In this case guessing that something is a number and optimizing a few bytes actually causes confusion.  Could we make the optimization opt-in instead?

**Comment by johnjaylward** [comment]
This has very little to do with the join export. The export is doing
exactly what it should.

The problem is that your version tag in the XML looks like a number but it
is not. You want it treated like a string, which it is. When the
`keepStrings` parameter is false (default), the XML parser guesses that
2.20 is a number. When it does, it converts it to a JSON Number, which
internally is stored as a Java `double`.

A Java `double` has no concept of maintaining insignificant digits. Thus,
when it's output it is written as 2.2.

You can try it yourself

````java
private final double d = 2.20d;
System.out.printLn("" + d);

````

**Comment by johnjaylward** [comment]
This has very little to do with the JSON export. The export is doing
exactly what it should.

The problem is that your version tag in the XML looks like a number but it
is not. You want it treated like a string, which it is. When the
`keepStrings` parameter is false (default), the XML parser guesses that
2.20 is a number. When it does, it converts it to a JSON Number, which
internally is stored as a Java `double`.

A Java `double` has no concept of maintaining insignificant digits. Thus,
when it's output it is written as 2.2.

You can try it yourself

````java
private final double d = 2.20d;
System.out.printLn("" + d);
````

**Comment by gaul** [comment]
@johnjaylward Agree that I blamed the incorrect code for the behavior I observed.  The behavior I observe is mostly to due with using a `Double` to represent the datum.  This branch uses a custom `MyDouble` will may demonstrate what I want to do:

https://github.com/gaul/JSON-java/tree/preseve-trailing-zeros

This allows me to parse `<a>2.2</a><a>2.20</a><a>2.20.1</a>"` as `{"a":[2.2,2.20,"2.20.1"]}`.

**Comment by johnjaylward** [comment]
If that PR is working for you than that should be fine. Personally, I don't see a benefit to this over the current XML processing. Most people would not want the number 2.20 to be output as a string as you have done here.

```json
{
  "someKey": "2.20"
}
```

I don't think a solution like this is going to make it into this library. It doesn't make sense to have this as default behavior, and the extra logic to make it do this make it harder to maintain. I believe that most use-cases would want to handle 2.20 as a number, not a string.

As a reference library, I believe having the XML maintain all string values is the best way to handle it.

**Comment by gaul** [comment]
Agreed, thank you for your feedback.
