### ISSUE TITLE
how to sort it

### ISSUE THREAD

**Issue by huangwei16800** [stleary/JSON-java#395]
JSONObject object=new JSONObject();  
      object.put("aaa",111);  
      object.put("bbb",222);  
      object.put("ccc",333);  
      object.put("ddd",444); 
but after print out,  order is not  the original order
System.out.print( maindata.toString() );
{"aaa":111,"ddd":444,"ccc":333,"bbb":222}

**Comment by huangwei16800** [comment]
how to keep original order

**Comment by MinnDevelopment** [comment]
JSON objects have no defined order, this library uses a HashMap for the JSON data which does not use insertion order. See all the previous issues that were closed.

**Comment by huangwei16800** [comment]
ok, thank you,  org.json will use insertion order in future ?

**Comment by johnjaylward** [comment]
No, never

**Comment by huangwei16800** [comment]
I'm sad, why not add a option to process it
Many people have already mentioned the proposal

**Comment by johnjaylward** [comment]
as stated in the other requests and in the FAQ and in the source, ordered JSON objects are "not JSON objects". By definition JSON object keys are unordered. If you are relying on order, then you are no longer using JSON, you are using something that looks like JSON but is not.

**Comment by migueltt** [comment]
As discussed several times and indicated by @johnjaylward, if an application relies on ordered attributes that's a wrong design. By definition, JSON attributes are just that - attributes - there's no sorting at all.
Think about Java attributes: do you rely on sorting? NO. So, why should you expect JSON attrs to be sorted?
Unfortunately, there are plenty of REST APIs that are being designed with "ordering" in mind.
Eg:
```
{
    "attr1" : {<details-about-record-one>},
    "attr2" : {<details-about-record-two>},
    "attr3" : {<details-about-record-three>}
}
```
The rationale for this design (and there are countless variations) falls into how such data should be processed (or, in some cases, displayed). This is totally wrong. Instead, the structure should use `JSONArrays`:
```
[
    {<details-about-record-one>},
    {<details-about-record-two>},
    {<details-about-record-three>}
]
```
`JSONArrays` are, by definition, ordered. Also, each element should have the same structure (attributes, "_datatypes_"). Otherwise, the application iterating and parsing the array will fail (or have countless if-else branches). If the `JSONArray` holds apples, don't put oranges and potatoes!

As suggested previously (and this is really in case of emergency):
1. Fork this repository locally and DO NOT PUBLISH IT. Using your internal gitrepo, make clear that this new repo is **WRONG, is not official JSON and should not be used for any application** because it breaks JSON specification - talk to your manager/supervisor/director/cto about this decision and why you need to use it, and why anyone should never use it again
2. Include an `_ordered ` flag in all constructors using `HashMap` - Eg `if (_ordered) then use LinkedHashMap`
3. Mark all your "ordered" constructors/methods as **deprecated**, because this is just a temporary solution and the related program generating the invalid-ordered-JSON-attributes must be changed as soon as possible
4. Write a note to yourself and all the team that **your code is wrong, should not be used for future releases, and should be updated** along with the related programs using ordered JSON attributes
5. Identify all those other programs (eg. REST endpoints) that are serving ordered JSON attributes and explain to the related teams that such programs are not following standards/specifications and must be updated as soon as possible - the longer this is not fixed, the harder will be - APIs spread light fire these days because of their benefits, but if such API is poorly designed, then it will spread the same deficiencies to other programs (eg. mobile devices, web applications, batch integration processes...). Also, other people using your API will be reluctant to use it, or, worse, start using your forked project...

I'm telling you this due to experience - a lot of big companies are starting to define their APIs, and in some cases are using this "ordered" design - which gives a lot of headaches to everyone...

**Comment by huangwei16800** [comment]
thank you very much , now i understand
