### ISSUE TITLE
LinkedHashMap using instead HashMap

### ISSUE THREAD

**Issue by acuna-personal** [stleary/JSON-java#425]
Thanks for your library!

It's so strange, but it's using an `HashMap` class instead of `LinkedHashMap`. It'll be cozily to port it to `LinkedHashMap`, because in some cases keys order are important (for example, fo read the `names ()` method in the loop).

I don't want to fork it because there're many updates in your library, so I don't want to freezy my own fork and always seaching for you project to get new updates manually)

Thanks in advance!

**Comment by johnjaylward** [comment]
Please read the [FAQ](https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects) or even the source code: https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L171

**Comment by erosb** [comment]
While it is a frequently requested change, according to the position of the maintainers it won't be changed, because JSON objects are specified as unordered. See here: https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects

**Comment by acuna-personal** [comment]
Yes, of course I read the FAQ, but I don't understand which problems it'll have with order? Following the specification will actual when it'll be cause a problems. Is there're a problems? I don't know about it. Specifications writing in the start of the conceptions, it don't handle the situations which it not handle, but unfortunately it's rarely rewritten, it's the main problem, not the way to caution the users to make the dangerous actions.

**Comment by johnjaylward** [comment]
For your example of the names, I would recommend doing something like this:
```java
JSONObject jo = new JSONObject();
// something that populates my object
List<?> names = jo.names().toList();
// java8 sort
names.sort(null);
//Java6+ sort
Collections.sort(names);

for(String name : names) {
     // do something with my names that are now in order
}
```

As for why this library will never offer sorted names out of the box is because it's a reference library. Implementations should never depend on sorting the names. If you have a specific use case that would require sorting the keys, then you should just something similar to what I made above.

**Comment by johnjaylward** [comment]
If you offer a pull request that adds a new method to the JSONObject called something like "namesSorted" which performs better than the above code, that would be a candidate for addition.

**Comment by acuna-personal** [comment]
Thanks, but it's a crutch. Think it's not needed to sort all collection while it'll be sorted by default. But I try to understand why it'll be dangerous? So that it is described in specification - it's a fact, but under any fact must rest the reason why this fact take part. For example, there's so dangerous to play childrens near the road (it's the fact), because they can run out onto it, for example, running for the ball, and get under the car (it's a reason why this rule take part), so, for example, if there're a flying cars will change the real cars in the future, this rule will be changed for the new realities, because the review of it has shown that it must be changed, except the old rule doesn't changed officially because it was accepted in the beggining of it conception and was changed due to its treatment.

**Comment by johnjaylward** [comment]
Are you just trying to troll here? Please come up with an actual use case why a reference library, whose sole purpose is to show that a specification works, should veer off the specification.

**Comment by acuna-personal** [comment]
It's so strange to troll on GitHub I think. I've illustrated it on the life example when the rules can veer off the specification by time. And as for JSON - it's logical that it might be order in the order you want to, because it's so strange to see that it have been added without any logic, even by its names. There's many realms when elements order is important - for example, in medical and banks auth strings to send it to server. As for me - I have side library, one method of which accepts only integer values, so it'll be nice to put em the guaranteed order which I want to to get it by index. Is it clear now? But why it's touched you so much? Seems you're not an author of JSON specification.

**Comment by stleary** [comment]
Hi @acuna-personal, your comments on JSON design are appreciated. You can get more insight into how the JSON design came about in the first place, including why JSON objects are never ordered, from Douglas Crockford, the original author of the spec and of this reference application, e.g. https://www.youtube.com/watch?v=-C-JoyNuQJs

**Comment by acuna-personal** [comment]
@stleary wow! I'd love to listen it all, but unfortunately English is not my native language (oddly enough :/). I know it good, but nearly an hour is so much for me. But is there're an articles or messages where I can read about why it *must* be a unordered? Thanks.

**Comment by johnjaylward** [comment]
because if being ordered is part of your requirement, it's not JSON any more. it's something that looks a lot like JSON, but behaves differently.

**Comment by acuna-personal** [comment]
@johnjaylward it's a result. But I'm trying to know why Douglas decided to made it unordered (the reason). And I want to talk with this library developer if you don't mind.

**Comment by stleary** [comment]
>>And I want to talk with this library developer if you don't mind.
This library was developed by Douglas Crockford, you should be able to find him on Google+.
@johnjaylward is the technical expert around here. I think he can provide the most authoritative answers regarding use of the JSON-Java lib. 

Well, I listened to the entire talk so that you wouldn't have to. Turns out the most interesting things he talks about are why there are no comments, why have a good-not-evil license, and why XML sucks. At around 12:00 he talks about JSON needing to be the intersection of all modern programming languages, and at 47:20 he mentions that JSON is also required to be a proper subset of JavaScript (JS collections are unordered). Also , at 9:30, he mentions this Java very reference implementation (it was on a different repo at that time). 

Hope that helps,
Sean

**Comment by migueltt** [comment]
@acuna-personal  The main reason for JSON Objects to be _unordered_ it's because a JSON Object is just that, an Object. The attributes should not be accessed by any special order, just like when you are using other languages. Note that I'm referring to **JSON Object attributes**. A JSON Array is a different story. Each array element is a JSON Object itself, and those elements are ordered.
There's a misconception that JSON content can be manipulated as a "file", therefore, the JSON content can be read and iterated sequentially - this is not correct. While there are different ways to do that (just like DOM vs. SAX for XML), such manipulations are discouraged. If you need order in your JSON, then just return those elements as array elements. If you need to access elements by order and the keys are used to identify some kind of metadata, then your JSON design (and by extension, your API) is, most likely, wrong.

**Comment by acuna-personal** [comment]
@stleary wow, you don't believe how I grateful to you for this timecodes, it'll helps me a lot with listen it, because I'm not limited only by that it must be unordered because it must unordered, like others. Don't understand how can it suits peoples by getting something new.

**Comment by acuna-personal** [comment]
@stleary ahah, for the library developer I means you ;) Hope that I'll understand it before than asking him)

**Comment by acuna-personal** [comment]
@migueltt well, thanks, I understand you and that it's a design question. But there's strange to listen that I can't using it for getting any data by it's keys in order because it's wrong solution, but I think it must be a reason why it's wrong. In other words there's a restriction which mades intentionally, but why? I don't believe than Douglas decides to make it as it because... yep, a JSONObject must be unordered because he want to have it unordered :/

**Comment by migueltt** [comment]
@acuna-personal To clarify this, let's see a Java example:
```
public class Person {
    public Person(...) {...}
    String name;
    String lastName;
    int age;
    Address address;
}
public class Address {
    public Address(...) {...}
    /* making all attributes public so they can be discovered using reflection. */
    public String line1;
    public String line2;
    public String city;
    public String stateProvince; // or whatever grouping exists in other countries
    public String country;
    public String postalCode;
}
```
A program will use these classes to create objects. The attributes are used arbitrarily without a specific order:
```
Person p1 = new Person(...);
System.out.println(p1.name+" "+p1.lastName);
```
Now, let's assume that there's a program that prints the address.
```
public static void printAddress() {
    // TODO Auto-generated method stub
    Address a1 = new Address();
    a1.line1 = "123 Elm Street";
    a1.line2 = "Suite 111";
    a1.city = "Raccoon City";
    a1.stateProvince = "Somewhere";
    a1.country = "USA";
    a1.postalCode  = "123123";
    Field[] fields = Address.class.getFields();
    for (Field attr : fields) {
        try {
            System.out.println(attr.get(a1));
        } catch (Exception _e) {
            // do something...
        }
    }
}
```
This code will access all the fields from class `Address`, but the order is not guaranteed - that is, different JVM implementations may return the attributes in different order - thus, this code is not correct.
The same principle applies when accessing and using attributes within a `JSONObject`.
`Person` and `Address` could be specify in JSON as:
```
{
	"person": {
		"name": "Willie",
		"lastName": "Coyote",
		"age": 32,
		"address": {
			"line1": "123 Elm Street",
			"line2": "Suite 111",
			"city": "Raccoon City",
			"stateProvince": "Somewhere",
			"country": "USA",
			"postalCode": "123123"
		}
	}
}
```
Remember: JSON is not _content in a format_ - in other words, JSON is not a sequence of characters arranged in a particular order.
Instead, JSON is data that follows specific syntactic rules and should be manipulated using standard mechanisms on any programming language.
`JSONObject` attributes are just like Java Classes attributes, but with a big difference: JSON is portable across different platforms - thus, each native JSON-library will access such attributes in different ways, and, there's no order at all on how such attributes are declared/defined/implemented...
Going back to our `Address` example, `line1` is not more relevant than `line2`. Both are equally important. It's just that we define `line1` before `line2` because it is visually correct (and to make the code more readable). The same applies for all other attributes.
Don't get confused with `JSONArray`s, which are JSON values listed in a particular order - values can be numbers, strings, null, boolean, arrays themselves, and JSON Objects.

**Comment by acuna-personal** [comment]
@migueltt hohooo, seems I'm at the StackOverflow :D Thank you very much! Okay, I understand that JSON is platform independent, but what is prevent us to arrange the elements as we want to arrange it like we arrange our classes in code for make it "visually correct", and seems now that any platform access this attributes in different ways, but how is it fraught with we makes some order? Of course it's not an order in conception, but if any platform think that it's an unordered in any case, so what is the problem to put it in any order what I want, because it's only readable order, not a factical? Or I missed something?

**Comment by migueltt** [comment]
@acuna-personal You can create your JSON as you like, in any specific order - so you can make it easier to read and troubleshoot. The question is about how your code uses that JSON.
If you want to iterate and go through the attributes in order, that's incorrect. As mentioned above, such kind of manipulation is not encourage (even though it can be done).
You must think about Data Models:
- In Java, you don't access attributes by iterating over them - you should specify `<class>.<attribute>` (or through get/set methods)
- When accessing a table in a SQL database, you don't access the columns sequentially, you should specify the column names ("attributes") - Yeah, there are ways to access them using an arbitrary order but that's error prone and bad code design
- Therefore, for JSON Object, despite attributes can be written/generated in a specific order, accessing them should not rely in that order - you must explicitly access them by reference (aka attribute names)
I've seen several API designs that try to solve general problems, by including not only data, but also "metadata instructions" - applications start parsing JSON and identify specific attributes to create visual components at runtime.
For example, content that must appear in a specific order (eg. header, content1, content2, content3, footer) by encoding data using naming conventions so when you receive JSON , you start iterating over the JSON Object attributes and depending on the attribute name they start creating panels/buttons/fields/etc. That approach is wrong.
If you really want to do that, you should specify such values using a JSON Array - but again, this has its own challenges as well, since your application will iterate over an array that contains elements with different structure. At the end, you application (say, mobile app) will spend a lot of cpu cycles just to parse and identify the correct attributes....
And we can go on and on on this, which is out of scope for github - you should open a thread on stackoverflow (if there isn't one already)

**Comment by acuna-personal** [comment]
@migueltt thanks a lot for explanation. I understand that it's encouraged to refer the JSONObject by its швы because the structure might be different, because it's like a crutch. We must write correctly, but in other way there's many side libraries which can work only with string arrays for example or JSON arrays, but developers using a JSON object in their projects for convenience but there's not neede to use any DB (for example to store data in JSON on server). So I compelled to change JSON objects to the LinkedHashMaps where the elements order is important. I wanted to use a JSON object for more flexible data types cast, but it's don't evolved, because specs doesn't recommend to use a LinkedHashMap because it's don't cool :/

P. S. Ahah, I know that I should open the thread on SO, but I didn't expected that it will look like it :D
