### ISSUE TITLE
I would like to strictly name the module

### ISSUE THREAD

**Issue by GedMarc** [stleary/JSON-java#451]
Hi There,

I would like to update the pom and build to generate the module-info class file, and strictly name this module.

Currently as an automatic module, you cannot perform a lot of JPMS functions, such as requires transitive, or evade the maven central deploy warning for unnamed modules.

This is purely the raw code, could I get a zip of the build and send back a finished zip for perusal?

**Comment by johnjaylward** [comment]
https://github.com/BGehrels/JSON-java holds the packaging for maven releases. Please peruse there and offer any merge requests at that location.

**Comment by johnjaylward** [comment]
Also, strictly speaking, this project must support back to Java6 still until @stleary mentions otherwise. So any module-info changes must not cause an issue with java6 runtimes.

**Comment by GedMarc** [comment]
It will still support JDK 6 so long as

- You build under JDK with source and target versions set to 1.6

This will produce the 1.6 output with the module-info correctly placed,

Thanks for considering it!, Hope you pull it in!

**Comment by GedMarc** [comment]
https://github.com/BGehrels/JSON-java/pull/3

**Comment by GedMarc** [comment]
You can view the build log and the output here (Guest user is enabled)

https://jwebmp.com/teamcity/viewLog.html?buildId=201982&tab=artifacts&buildTypeId=ThirdPartyBuild_BuildOrgJson

Thanks!

**Comment by stleary** [comment]
Will existing developers have to change their build process to use the new build?

**Comment by GedMarc** [comment]
Not at all, this simply adds the module-info class file into the final packaged jar

I wanted to double check the class file version, it is indeed JDK 1.6 version 50

![image](https://user-images.githubusercontent.com/5367513/49046022-7651bc00-f1db-11e8-9636-3b07ef1c18f1.png)

**Comment by xzel23** [comment]
Hi, I have created a [fork](https://github.com/xzel23/JSON-java) that adds modules, but I build it using gradle. I could contribute the module-info.java files. I would be happy to help to get module-info into trunk.

**Comment by GedMarc** [comment]
I see you've moved the classes to a higher version of Java,

Thanks!
This strictly naming is definitely needed so you don't have to specify requires org.json in the consuming module but only the dependency, and to keep org.json out of the java.base root module (automatic named module placement)

To be honest, I do prefer my method, it keeps the libraries perfectly in tact without any code changes of any kind, or bumping of JDK's. 
I would also like to still be able to use the official build repository, rather than otherwise.

If worst comes to worst, on all these projects that require the push forward into JPMS, I'll be placing them onto the com.jwebmp maven group, and utilizing all the updates  from there :)

P.S. Gradle is the android native build tool. You shouldn't actually be using it for Java. While Maven Gradle Ivy and Grunt can all build Java, and they can all build android native, each was designed and built specifically with a purpose in mind. You should be using the build tool built for Java to enable advanced functions that are required post JDK 7 like annotation processor paths, annotation arguments, processing updates and manipulation, etc
So I wouldn't use this fork either based purely on the build tool choice. But that part is my opinion.

**Comment by xzel23** [comment]
@GedMarc: Sorry, but I think I only understand half of what you try to say.

I think adding the module-info.class files will probably break things for some developpers. That's also the reason why I did not try to contribute back. I have to research because it's been some time, but I remember these issues:

While module-info.class files should be ignored when used with older Java versions, at least some tools choked on this, IIRC these were among others
- SpotBugs
- JUnit 4
- Eclipse
- the Android toolchain

Another solution would be Multi-release Jar files, but with more or less the same issues.

If you don't want to abandon Java 6 compatibility (a version that has been unsupported by Oracle for several years now), you should probably not force your users to use the newest versions of these softwares (I don't even know if all problems have been solved in the meantime).

So, at least some  developpers *will* have to change their build process or dependencies. And I also doubt all those new versions will still be compatible with Java 6.

IMHO it would be great to have a truly modularized version in trunk, but I think you have to make a compromise. You cannot have it and still be compatible with JDK 6 and the tools used to maintain Java 6 based software.

Concerning your comment about Gradle: Maven is not *the* build tool for Java. If there's a tool that deserves that name, it should still be Ant. Just because Gradle has been adopted as Android's standard buid tool doesn't mean it's not suitable for Java. Following your rationale, you shouldn't even use Java for anything other than Android development, right? But I think this really doesn't belong here, and if you want to discuss build tools further, you can rather contact me directly. Gradle was simply the tool I chose because I could reach my goal faster.

**Comment by johnjaylward** [comment]
@xzel23 The PR that @GedMarc provided only adds the module.info file in the JAR during the packaging process. It does not add it to this project. See his PR at https://github.com/stleary/JSON-java/issues/451#issuecomment-441779708

**Comment by johnjaylward** [comment]
Also, as a side note, please leave build tool discussions out of this project. They are not relevant.

**Comment by xzel23** [comment]
@johnjaylward But there's a packaged Jar at mavencentral, linked from the main github page. Won't it add the module-info once this is merged? I think it should, but I also think this could break builds.

**Comment by xzel23** [comment]
> ^^ This is completely incorrect and none of the above is true in any regard.

Can you elaborate? Have you tested? All tools? Because I definitely had problems as I have written above. I agree that there *should* not be any problems, but for example some tools simply [cannot handle the non-standard file name](https://github.com/spotbugs/spotbugs/issues/408) containing a dash. That bug has been fixed in the meantime, but the fixed version (3.1.x) is incompatible with Java 6. And I had problems with other tools as well. Maybe there are workarounds, but how can you say it's not true?

In my Jar, I only compiled the module-info with JDK 9, the remainder with JDK 8 compatibility (I know, yours is JDK 6). So the resulting Jar should be more or less the same as sneaking in a JDK-9 compiled module-info after the build.

I think this should be looked into before releasing a modularized Jar. Can you provide me with a binary Jar so that I can try it against the tools that I had problems with?

**Comment by johnjaylward** [comment]
Are you able to just stick the module-info file into a version folder in the jar? Does it have to be root-level?

**Comment by johnjaylward** [comment]
answered my own questions: https://openjdk.java.net/jeps/238#Modular-multi-release-JAR-files

looks like module-info need to exist both at the top level and in any version folders. 

Would be nice if you can test it out with it missing at the root level and see if it works in a couple JVMs

**Comment by johnjaylward** [comment]
Ah, I've always like Stevens work. Joda was a go-to for me for years. And I agree with that blog 100%. My company is on Java8 and has almost no plans to move to Java11 because so far in testing with java 9&10 it has been a major undertaking with lots of incompatibilities. It will probably be another year or 2 before we fully make the switch.

As for the module-info at root, I must have been reading too quick, I could have sworn it said the exact opposite.  Thanks for testing it out.

**Comment by GedMarc** [comment]
whoop whoop, JDK 6 finally EOL!!!!

JDK 6 EOL = December 2018
JDK 7 EOL = July 2019
JDK 8 EOL = March 2022
JDK 9 EOL = March 2018
JDK 10 EOL = September 2018
JDK 11 EOL = September 2026

**Comment by GedMarc** [comment]
@johnjaylward 9 and 10 were JPMS Alpha and Beta, and yes I agree were absolutely horrid ;)

It looks like 6 and 7 are completely out next year, I'm not sure if you have 2 years to make the switch. JRE 8 looks to have an extended life span.

**Comment by stleary** [comment]
Is there consensus about whether to proceed?

**Comment by xzel23** [comment]
@stleary I suggest someone who uses this library on Android tries @GedMarc 's build. If it works for him, I'd proceed.

Whether to drop support for Java 6 and 7 now is another point. I think yes, it's time to move to Java 8 at least (because it's LTS), although I know that probably many companies have not upgraded yet (but if it's ok for them not to upgrade the JDK, it should be ok not to upgrade JSON as well).

**Comment by GedMarc** [comment]
I don't think we should drop jdk 1.6 support until the jvm no longer supports running it,
I say yes please pull it in, i have a week and then it's either this library or the one i'm dev'ing on ;)

**Comment by stleary** [comment]
Sorry, was not clear. Question has been updated, feel free to edit your answers or provide new ones.

**Comment by GedMarc** [comment]
@stleary 
The changes don't affect JDK 6 and no one will feel it except for those using jpms, i don't think it's needed to offer a separate package, simply a new release with the changes?

**Comment by johnjaylward** [comment]
@stleary the PR earlier in this thread has links to a JAR file which was built using the changes @GedMarc made to allow for the module-info within a Java6 JAR. I think we should get a few people to test it on java6-8 JVMs and then make a decision. If the changes @GedMarc made work as-is across older JVMs, then I think we should plan on using it as a measure to support newer JVM features while maintaining our Java6 byte code.

I'm not a fan of using multiple packages unless we actually add language/code features for the high versions of supported JVMs (like streams, lambda, Optional, etc).

**Comment by stleary** [comment]
@GedMarc feel free to create a pull request to update the readme to offer users the option of downloading your alternate jar. It can appear at the top of the readme.

**Comment by johnjaylward** [comment]
@stleary the PR is against @BGehrels repository which would update our future releases to support this. I don't think updating the readme is the way to go.

**Comment by stleary** [comment]
Missed that, sorry. The changes should be made to a fork of @BGehrels repo, not the original. No changes to how JSON-Java releases are packaged should be made at this time. If you don't want to update the readme, I guess people can learn about it from this issue.

**Comment by xzel23** [comment]
> I'm not a fan of using multiple packages unless we actually add language/code features for the high versions of supported JVMs (like streams, lambda, Optional, etc).
 
@johnjaylward: Being able to create a redistributable runtime that only contains what's needed for your application to run is a new feature that is enabled by providing strictly named modules. As an example, I have created a markdown-viewer application that is ready to run with 78 MB in size (application + `jlink`-generated JVM) as opposed to more than 250 MB (JVM alone) when not using `jlink` to create a stripped down version of the JVM. `jlink` does not work with automatic modules.

**Comment by johnjaylward** [comment]
Creating a second package (whatever we call it) may give a false impression that newer JVMs are implicitly supported. My main issue is that going forward, JVMs (9+) are [not guaranteed to be backwards compatible](https://blog.joda.org/2018/10/adopt-java-12-or-stick-on-11.html). Granted we are not using features that a likely to be deprecated/removed and cause compatibility issues, but it's still a valid concern that library maintainers need to take into consideration.

Using the approach from @GedMarc seems logical and a small footprint, but as I've stated multiple times, the resulting JAR needs to be tested against multiple JVMs. In JVMs 9+, it would also need to be test on both the module path and the classpath ([as noted in Stephen's blog linked earlier in this thread](https://blog.joda.org/2018/03/jpms-negative-benefits.html)).

It sounds like @stleary does not want to take on that maintenance task at this time. If that's the case and @GedMarc's PR will not be rolled into the main release branch, then going with the README change and linking to the PR branch is probably the best bet at the moment.

**Comment by GedMarc** [comment]
Hmmm, 
This was mostly a "I love your library let's keep it relevant", for my purposes I don't need anything under JRE8 and can go the route of custom-built libraries, also I tackle the build and deploy strategy a little differently for multiple repo destinations so anything I do to it outside the scope of keeping the original package in tact will completely destroy any commit and pull request I do here on.

I think I'm going to rather go to my fork and go the lint and rework for jre8, technically JDK6 died off 2 days ago and with 7 falling away in 6 months.

Sadly I really do need a named module so I can't use this one anymore.

**Comment by BGehrels** [comment]
Hmm, it's sad that @GedMarc closed this issue, because i consider the discussion highly valuable.

I'm also highly irritated by the way motivated contibutor is bounced without even a simple "Thank you for the work you've invested and your efforts to keep our library up to date. We sadly can't merge it but highly appreciate your contribution and input to this discussion".

The decision to stick to Java 6 was taken 3 years ago in https://github.com/stleary/JSON-java/issues/156 in order to support Android versions <4.4. While back then, ~50% of the android devices still used <4.4, [it's just 3,5 % nowadays](https://developer.android.com/about/dashboards/) - and given the short live of mobile devices nowadays i guess it will be much less in 6 months from now. So maybe it's time to drop this requirement. Spring, for example, dropped support for java 6 and 7 with version 5 in september this year. I wouldn't go that far since Java 8 is not fully supported in Android < 7, which is nowadays still used by ~50 % of the devices. Maybe @snodnipper - who advocated for Java 6 support back then - can contribute a bit of expertise here?

While i understand the argument that manually testing against `n` different jdks/jres is a huge burden, i guess that's what CI systems like https://travis-ci.org/ are made for. Travis also integrates nicely with github and can run a test, build and deploy on a wide range of different environments.

Those benefits will be much easier to leverage if we have the pom, the tests and the code in one place. This raises the question: Which value do we get from splitting the unit tests and the code in two distinct repositories? Which value do we get from maintaing the maven central build in yet another seperate repository with a seperate maintainer?

So maybe, instead of draining contributors of their motivation, we should see java 11 as a chance to renew the project and put it on stable, more maintainable feet?

**Comment by johnjaylward** [comment]
I agree. I think it's a little premature to close this issue yet. I think we can find a good resolution that will work. 

I know we have some restrictions on public API changes based on the hands-off from Douglas, but I think merging the test cases back into mainline and possibly Implementing some build tool integration are a great place to go forward.

We should highly consider these things going forward. There are mmultipletmultipletimmmultipletmultipletimes even recently that contributors have had trouble finding tests, or in this case the distribution POM.

Consolidating the projects should simplify a lot, both new contributors and even old contributors like myself.

**Comment by GedMarc** [comment]
I closed the PR and issue cause I need something working for the weekend :)
With the changes that I'm going to make, (I don't want to branch off and config CI again), the PR would never be able to be pulled in. Also going off on my branch instead, I've bumped up my version to min JRE8.

I think it's pretty simple and straight forward, there's nothing funny going on, still JDK6 build nothing changed there at all, it's purely just a moditect + module-info in the build (the PR was on the right github repo I think)

I've already punched through a large portion of the library so I can't re-open the PR, the group, build method, StringBuffer->StringBuilder, Lint'ing and etc have all already been changed. There's like 160 more lint's to get my branch to an acceptable level for JRE8 (for me) so not going to revert it.
https://github.com/GedMarc/JSON-java

@johnjaylward The build and pom structure is a bit weird 👍

**Comment by GedMarc** [comment]
Would you like me to provide a PR?

Thanks for reopening

**Comment by stleary** [comment]
@GedMarc, Yes, please add a PR.

**Comment by GedMarc** [comment]
Update please -

Why is this not pulled in, Why is there no feedback

**Comment by johnjaylward** [comment]
@stleary I've commented on the linked PR, I'm no subject expert on modules, but the changes look like they shouldn't cause any issues with backwards compatibility to me.

**Comment by johnjaylward** [comment]
@stleary If you could also provide guidance on if we should do a new package release or not to get the named module support in (as opposed to the auto module naming we have currently), that would be great. I think a new release would be the best course myself just so we can get community feedback if there are any issues.

**Comment by stleary** [comment]
@johnjaylward, agreed, I also commented, and thanks for doing the analysis.

**Comment by jordanamr** [comment]
> whoop whoop, JDK 6 finally EOL!!!!
> 
> JDK 6 EOL = December 2018
> JDK 7 EOL = July 2019
> JDK 8 EOL = March 2022
> JDK 9 EOL = March 2018
> JDK 10 EOL = September 2018
> JDK 11 EOL = September 2026

Whoop whoop, we are in 2020, what's going on with this issue?

**Comment by GedMarc** [comment]
See end comments here

https://github.com/BGehrels/JSON-java/pull/4

**Comment by GedMarc** [comment]
JDK 8 EOL'd last year Jan btw

**Comment by stleary** [comment]
Comment added to [PR 4](https://github.com/BGehrels/JSON-java/pull/4)

**Comment by stleary** [comment]
Please see comments in https://github.com/BGehrels/JSON-java/pull/4. Looks like no further work is planned for this issue.
