### ISSUE TITLE
Implement JSON-P Specification

### ISSUE THREAD

**Issue by amihaiemil** [stleary/JSON-java#464]
It would be nice to add your implementation behind the JSON-P interfaces: https://javaee.github.io/jsonp/

JSON-P is the standard specification for Json in the Java world, starting with Java EE 7. I.e. the following paragraph from the README is **not true** for a while now:

```
This is a reference implementation. There is a large number of JSON packages in Java.
Perhaps someday the Java community will standardize on one. Until then, choose carefully.
```

[Here](https://github.com/javaee/jsonp) is the original JSON-P repo containing also the reference implementaiton from the Glassfish team (but you don't really need that, I guess you could just implement most interfaces with the code you already have). 

[Here](https://github.com/eclipse-ee4j/jsonp) is the current JSON-P repo. Since 2018 Java EE has moved from Oracle to Eclipse Foundation and is part of the bigger umbrella project called "Eclipse Enterprise For Java".

Who knows, if your implementation is better, it may get included into a Java EE platform?

**Comment by GedMarc** [comment]
Wait. What?
Jackson is the provider for EE6 and under, from Glassfish/Payara through to EAP/Wildfly, tomcat Tomee and Jetty.
The reason why it is called Json-P is because Jackson took "JSON" 

I think you have your timeline all kinds of wrong here,

**Comment by amihaiemil** [comment]
@GedMarc Jackson maybe the provider for EE6 and under, I'm not sure. I'm talking about EE 7 on. From EE 7 on, Glassfish/Payara use the RI I linked above and Wildfly/EAP still use Jackson, I believe (however, I'm not sure if Jackson didn't implement JSON-P, by any chance).

I'm not sure about TomEE either. tomcat and jetty don't fit into the discussion, they are simple servlet containers, not Java EE platforms :) 

It's called JSON-P because it stands for Json-Processing, it has nothing to do with Jackson.

**Comment by johnjaylward** [comment]
JSONStringer and JSONWriter already have interfaces like this. Unless I'm missing something, I doubt we will implement anything "JSON-P" specific unless someone submits a very clean PR.

**Comment by amihaiemil** [comment]
@johnjaylward I'd say you should implement it simply because you're going against the current. There is a specification now, which is supposed to keep applications clean and lightweight (especially Java EE ones).

I opened this Issue because I keep seeing this library being used in Java EE 7+ applications. The Java EE world is already confusing for most developers, we should at least clarify this simple Json topic -- the fact that the library has ``org.json`` groupid doesn't help either, it gives you the feeling that "this is it!" when, in fact, it's not :)

**Comment by johnjaylward** [comment]
This project has the "org.json" group ID because it was created by the original JSON specification creator Douglas Crockford who registered the group. Group IDs imply nothing other than the creator/maintainer.

As for a specification. the JSON-P spec required users to implement an interface in the `javax` namespace, which usually signifies an external dependency. This project does not use external dependencies.

If/when the JSON-P spec gets added to the JDK/JRE as a standard library, then it will be a candidate for inclusion in this project.

**Comment by amihaiemil** [comment]
@johnjaylward 

> which usually signifies an external dependency.

Yes, a dependency containing 8 or 9 Java interfaces. It's really negligeble. And those interfaces do provide methods to work with standard Java SE stuff such as Reader and InputStream.
 
JSON-P *is* already a standard library, provided by the Java EE 7+ implementors,

Let me put it simpler: if I have a Java EE 7+ webapp using your library, that's a few kilobytes or megabytes in my deployable which should not be there. But they are there, my deployable is fatter,, because I'm not using the JSON-P interfaces (for which the implementation is already up on the server), I'm using your classes, so I have to take your impl with me.

Anyway. My 2 cents are spent here, I guess. Feel free to close this if you don't see any benefit :)

**Comment by johnjaylward** [comment]
This project is meant as a stand-alone implementation using standard java. Including a 3rd-party library that is not part of the JRE breaks that. It's that simple. It's not about any other "benefits" or not or how large the dependency is.

Java EE is not part of the JRE. JSON-P being standard in Java EE jas nothing to do with Java itself. That's like siting some random Tomcat dependency as a reason for this project to also include that dependency. It requires a significant amount of extra libraries in order to run a JavaEE application. Java EE as a reason for this project to change it's goals is really not a good argument.

From what I've seen over the years, is most large applications dropping support for this library due to the license "restrictions" more than anything else. I don't think us "not supporting" JSON-P is a major setback.

**Comment by stleary** [comment]
@amihaiemil Thanks for opening a conversation about this issue. I think it might not be suitable for this reference application, for the reasons cited by @johnjaylward. Feel free however to review the [Wiki FAQ](https://github.com/stleary/JSON-java/wiki/FAQ) and submit a pull request if you think it fits with the project goals.
