### ISSUE TITLE
Should JSONPointer.query ALWAYS throw exception on non-exist key?

### ISSUE THREAD

**Issue by pingu8007** [stleary/JSON-java#471]
Currently, query on non-exist key have 2 possible result. Assume we have following data:
```json
{
  "a": {
    "b": {
      "c": "success"
    }
  }
}
```

If I query on `/a/NON_EXIST/c`, `JSONPointerException` is thrown.
If I query on `/a/b/NON_EXIST`, `null` is returned due to the inner call to `JSONObject.opt`.

I've checked the RFC document and how query on non-exist key should be handled is up to implementation.

Should we unified the underlying logic to either returning null, or throwing exception? Since query may throw exception and above result is undocumented, I've seen many user misunderstanding that this method won't returning null.

**Comment by erosb** [comment]
Hi!

I think the original idea was to make the behavior similar to NPE-s in java (ie. throw an exception when the null reference needs to be dereferenced for further evaluation steps, otherwise evaluate to null).

Changing this behavior of the `query()` method would be BC-breaking for some users, so I don't recommend doing that, but we may introduce an overloaded `query(EvaluationOptions)` (or whatever) method which lets the caller explitly specify this.

**Comment by pingu8007** [comment]
Thanks! I never thought there are historical reasons. If so, it would be better to document it somewhere.

Overloaded configurable method may be help a lot on chaining access to value, in case of which part missing isn't matter.

**Comment by stleary** [comment]
@pingu8007 Thank you for catching the inconsistent behavior and letting us know. Agreed that changing existing behavior is best avoided. No objection if anyone wants to propose text for the readme or for a new wiki page. Also OK if someone wants to submit a PR for an overloaded version of query(). Will leave this issue open for up to a month or so, in case  anyone wants to follow up.

**Comment by stleary** [comment]
Closed due to inactivity for 1 month. Feel free to open a pull request if you want to address this, or open a new issue to propose readme/wiki text.
