### ISSUE TITLE
Large numbers parsed as strings

### ISSUE THREAD

**Issue by slisaasquatch** [stleary/JSON-java#497]
Here's the sample code:
```java
  @Test
  public void testLargeNum() {
    final JSONObject j = new JSONObject("{\r\n" +
        "  \"foo\": 10000000000000000000000000000000\r\n" +
        "}");
    // The following line prints class java.lang.String!!!
    System.out.println(j.get("foo").getClass());
  }
```

**Comment by stleary** [comment]
@slisaasquatch Thanks for bringing up this issue; interesting that numbers are handled differently depending on whether chars like '.' or 'e' are present. Do you want to present a case that the code is not in compliance with [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and/or [RFC8259](https://tools.ietf.org/html/rfc8259)?  Otherwise, I believe this behavior has been in the code since the [first commit for this repo](https://github.com/stleary/JSON-java/blob/5b18f02eeedcdab344b34979372483050de13823/JSONObject.java) (see stringToValue()).

**Comment by johnjaylward** [comment]
I was pretty sure we changed this behavior a few years ago to use BigInteger instead for these cases. Let me try with a recent build

**Comment by johnjaylward** [comment]
Ah, we never made the full switch. I left notes in the code on where it would be handled though:

https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L2173-L2218

**Comment by stleary** [comment]
I think that code review is still open, if you mean #453, due to changes to existing behavior.

**Comment by slisaasquatch** [comment]
> @slisaasquatch Thanks for bringing up this issue; interesting that numbers are handled differently depending on whether chars like '.' or 'e' are present. Do you want to present a case that the code is not in compliance with [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and/or [RFC8259](https://tools.ietf.org/html/rfc8259)? Otherwise, I believe this behavior has been in the code since the [first commit for this repo](https://github.com/stleary/JSON-java/blob/5b18f02eeedcdab344b34979372483050de13823/JSONObject.java) (see stringToValue()).

Thanks for your quick response.

I checked the specs for numbers [here](https://tools.ietf.org/html/rfc8259#section-6), and all it says about really large numbers is that implementations may approximate the numbers to fit double precision floating points, and says nothing about turning large number into strings. And in this case, the number actually does fit into a double precision floating point.

**Comment by johnjaylward** [comment]
@stleary, yes. that PR would fix this and open up the parser to have more exact representation of what was in the original JSON text.

**Comment by stleary** [comment]
My best guess is that this implementation only guarantees integer interoperability to 2 ** 53 per the spec via Java Long type, and Double was only used to support decimal and scientific notation.  I think if you have access to the software that generates very large numbers, it is probably better to just serialize them as strings.

**Comment by stleary** [comment]
@johnjaylward Agreed, exact representation is preferred. I wanted to keep the PR open to see if there is a way to implement it as an option, to ensure existing applications don't break.

**Comment by johnjaylward** [comment]
@stleary, gotcha. If I have time, I'll see if I can come up with a "parser config" type object that could be used to configure how items are parsed.

@slisaasquatch as a work around for your specific example, you can represent the number with a decimal point, or use scientific notation to force the parser to try to use a double as the backing type instead of an integer.

```json
@Test
  public void testLargeNum() {
    final JSONObject j = new JSONObject("{\r\n" +
        "  \"foo\": 10_000_000_000_000_000_000_000_000_000_000.0\r\n" +
        "}");
    // The following line prints class Double!!!
    System.out.println(j.get("foo").getClass());
  }
```

OR:

```json
@Test
  public void testLargeNum() {
    final JSONObject j = new JSONObject("{\r\n" +
        "  \"foo\": 1e31\r\n" +
        "}");
    // The following line prints class Double!!!
    System.out.println(j.get("foo").getClass());
  }```

**Comment by javadev** [comment]
```java
  @Test
  public void testLargeNum() {
    final JSONObject j = new JSONObject("{\r\n" +
        "  \"foo\": 10000000000000000000000000000000\r\n" +
        "}");
    // The following line prints class java.lang.String!!!
    System.out.println(j.get("foo").getClass());
  }
```

The expected value is `class java.math.BigInteger`.

**Comment by johnjaylward** [comment]
@javadev yes. This has been a known limitation of the library for quite some time. When a number can not be parsed as an integer or a double, it stores it as a string internally. In our case, we only parse using a `double` if the value "looks" like a double (contains a `.` or `e`), otherwise we parse it as a `long`.

In cases where the caller requires a number, this can be worked around by using the `getNumber`, `getDouble`, `getBigInteger` or `getBigDecimal`, or their `opt*` equivalent methods to get a consistent numeric type.

According to the JSON specifications, a parser has no obligation to handle values that don't fit in 64-bit integer or floating point data type (`long`, or `double` in Java). This parser historically tried to maintain the value as close as possible by keeping the value as a string instead of ignoring it or throwing an exception.

**Comment by stleary** [comment]
Closed due to working as designed.
