### ISSUE TITLE
Json to xml - Attribute issue.

### ISSUE THREAD

**Issue by shashi2k6** [stleary/JSON-java#504]
Hi Team,

The below sample works fine :
`<student><name>Neeraj Mishra</name><age>22</age></student>`
`{"student":{"age":22,"name":"Neeraj Mishra"}}`

The below item is not working - attributes is shown as separate tag here :

` {"student":{"age":22,"name":{"content":"Neeraj Mishra","type":"employee"}}}`
`<student><name>Neeraj Mishra<type>employee</type></name><age>22</age></student>`

Expected output 
`<student><name type="employee">Neeraj Mishra</name><age>22</age></student>`

Thanks

**Comment by stleary** [comment]
@shashi2k6 thanks for raising this issue. JSON-XML conversion is necessarily imperfect. From your example, I cannot be sure if the problem is converting to XML or from XML. For now I will assume it is **from** JSON **to** XML. You may find that the API in JSONML.java works better for you. 

I think this project would benefit from clear documentation about how XML is handled. If anyone wants to work on this, feel free to submit a wiki page to this project: https://github.com/stleary/JSON-Java-Wiki-Pages

**Comment by stleary** [comment]
Closed for lack of activity.
