### ISSUE TITLE
private access modifier used for NULL class even when its instance is used in JSONArray class.

### ISSUE THREAD

**Issue by Hemant27031999** [stleary/JSON-java#511]
Hello JSON team. I am a little confused about the `NULL` subclass being private.
The subclass `Null` inside `JSONObject` class is having private access modifier but the object instantiated using it in the same class i.e `NULL` is used in JSONArray class also. No error is thrown at compile time because this `NULL` object is instantiated by polymorphism and is of Object type at compile time:
`public static final Object NULL = new Null();`
However, during runtime, it can throw an error. Can you explain the reason behind using the private modifier for NULL class when its object is used in other classes also?

**Comment by johnjaylward** [comment]
The `Null` class is meant to be used as a singleton through `JSONObject.NULL`. The only instance should be the public static instance on `JSONObject`. There is no reason to have a higher access modification than private since all direct use of the class is handled within the same parent object. All external calls only call public methods that exist on `Object`.

There is no way that I know of for the code to throw a runtime exception that I have seen. Do you have a test or example that demonstrates that behavior? Can you provide runtime environment information for it as well?

**Comment by stleary** [comment]
Closed on the presumption the question was answered.
