### ISSUE TITLE
JSONObject.put() and JSONArray.put() do not call wrap()  (Issue from #552 pull request)

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#555]
From @johnjaylward: I just noticed the JSONObject.wrap method call here (and in the other addAll method), and I think we may have an issue with consistency. If you notice both the JSONObject.put(String, Object) and JSONArray.put(Object) methods do not do any "wrap" calls to the values. However, the constructors (before the new addAll methods) both wrap values. I feel like this may have been an oversight at some point. Changing the wrap to happen consistently in the put methods breaks a number of tests.

@stleary some guidance on what to do in this case would be appreciated.

so, to this effect, I actually worked around it in my own copy by adding the wrap calls to the put methods

**Comment by stleary** [comment]
If it's an oversight, then at least in the cases of JSONObject.put(String, Object) and JSONArray.put(Object) it seems to go back to the first commit in 2010. If that is the case, I would lean towards adding a note to the readme but not changing the code, even if it is a bug. But let me know if you think it is more recent.

**Comment by johnjaylward** [comment]
No, I think it's something that's always been there. Changing it at this point would be a fairly large breaking change, so unless we get a lot of complaints about it, I'm guessing it should stay as it is. 

It did bug the heck out of me, which is probably why I "fixed" it in my personal copy. It really bugs me because `JSONObject.put(String, Map<?,?>)` will `wrap` the values withing the map, but `JSONObject.put(String, Object)` just puts the value in raw with no wrapping. I just think it was missed in the original implementation and no one bothered to complain, either because it didn't fit their use cases, or they just worked around it.

**Comment by stleary** [comment]
Closed due to no action being taken at this time
