### ISSUE TITLE
Change HashMap to ConcurrentHashMap

### ISSUE THREAD

**Issue by Dauthjan** [stleary/JSON-java#559]
Faced issue while updating JSONObject.

>>What I was trying to achieve :
Convert JSON to XML. 
>>Example
Tried with JSON {"01":"Some Value"}
XML generated <01>Some Value</01>
This seems to be an invalid XML
>> Solution I approached
Iterate the HashMap, if Key matches some RegEx, Create New Key as per rules defined, Put values and remove old Key. Ran into ConcurrentModificationException. 
Changed HashMap behind JSONObject to ConcurrentHashMap to achieve the result. 

Please suggest if the result can be achieved in some other way or changing HashMap to ConcurrentHashMap would be safe?

**Comment by johnjaylward** [comment]
I don't believe changing to a `ConcurrentHashMap` will fix that issue. I think what you actually want to do is return a new JSONObject from your transform.

psudocode:
```
function CleanXmlKeys(JSONObject source) returns JSONObject
  NewJO is a JSONObject
  for each key in source
    NewJO.put(fixKey(key), source.get(key)) // may need to do recursion here if sub-JSON Objects are expected
  end for
  return NewJO
end function

**Comment by Dauthjan** [comment]
Hi @johnjaylward  The solution that you suggested is what I approached earlier. Just to change the keys of the HashMap, creating a new HashMap will be efficient? Specially while dealing with large json? I fear that may result into heap memory issue. 
I used simple iteration logic (https://www.baeldung.com/jsonobject-iteration) and replaced key.
Changing HashMap to ConcurrentHashMap actually solved the issue for me. Correct me if I'm wrong.

**Comment by johnjaylward** [comment]
yes, if you are worried about heap, then in-place replacement will be better.

To replace the keys with the current hashmap, the way you would do it is to create a second set of the keys:

```java
voidCleanXmlKeys(JSONObject source) {
  Set<String> keys = new HashSet<>(source.keySet());
  for (String key : keys) {
    Object val = source.get(key);
    source.remove(key);
    // may need to do recursion here if sub-JSON Objects are expected
    source.put(fixKey(key), val); 
  }
}
```

The idea is that you are iterating a new set of matching keys, not the JSONObject itself. So the delete/insert works since the iterator is for a different collection than the one being modified.

If you aren't going to spawn off multiple threads, I would recommend against using the concurrent collections as they work slightly slower in single threaded operation.

**Comment by stleary** [comment]
Closed due to concerns having been addressed in the comments, and no code changes planned at this time. Post here if you think there is still an unresolved issue.
