### ISSUE TITLE
Replace HashMap with LinkedHashMap in JSONObject

### ISSUE THREAD

**Issue by clentfort** [stleary/JSON-java#66]
In my opinion it would be useful to replace the `HashMap` in `JSONObject` with a `LinkedHashMap` to maintain the order of the inserted values. This is would be really helpful if one wants to create JSON files that are easy to read and easy to compare with the original files. Also it is more helpful when iterating through the objects since the values come in the order you expect them.

**Comment by AmirHossein** [comment]
i think it should be great if make it optional. Ordered keys is good for some cases such as public api.

**Comment by johnjaylward** [comment]
No. All JSON specifications specifically say the keys are unordered. If a public API is using ordered keys, then they are using JSON incorrectly.

**Comment by stleary** [comment]
Agree with @johnjaylward. A JSON reference app has to follow the spec.

**Comment by Tilko** [comment]
>  If a public API is using ordered keys, then they are using JSON incorrectly.
you put your mind in jail or what ? ...

**Comment by johnjaylward** [comment]
Yes. JSON was made for data exchange. If you are relying on some ordering of keys, Then you are using something that looks like JSON, but is not. If you need ordering in JSON, you use an Array, not an Object.

**Comment by Tilko** [comment]
I tried to imagine a case where the choice of a particular order could be a bad idea, guess what, I did not find any because the JSON spec let us free about it. Have I a lack of imagination ?

**Comment by stleary** [comment]
@Tilko Thanks for offering your thoughts on this issue. In this case the project is sticking with unordered due to [RFC 8259](https://tools.ietf.org/html/rfc8259):  "_An object is an unordered collection of zero or more name/value pairs_".

Let's give the last word to Douglas Crockford, who invented JSON, was the author of this project, and left this comment in issue #37: "_This has been tried. What happens is people make applications that depend on that ordering, which breaks interoperability._"
