### ISSUE TITLE
Duplicate key processing?

### ISSUE THREAD

**Issue by XIAYM-gh** [stleary/JSON-java#840]
Currently, the JSON library simply throws JSONException when meeting duplicate keys, although most of the time it doesn't happen, but it's inconvenient when I want to process some *imperfect* JSON data.

So I think it's a good idea to add some methods to set the processing strategy, decides whether to override or skip or throw a exception.

Um, I think the method can be added to the constructor, just like the following code:
```java
new JSONObject(jsonStr, DuplicateStrategy.OVERRIDE);
```

(My native language isn't English, so maybe there're some grammar mistakes, thanks.)

**Comment by stleary** [comment]
@XIAYM-gh Thanks for submitting this issue. While the spec does not seem to disallow duplicate object keys, I am not sure how it would work in JSON-Java. For example, what should JSONObject do with a duplicate key, since it cannot be stored as-is?
If implemented, it will need to be opt-in using JSONParserConfiguration to capture the option. That class is implemented in #805, which is stalled at the moment.
Suggest that you try forking the project, implementing non-unique key support in a way that makes sense to you, and get an idea of how it might affect the rest of the library.

**Comment by XIAYM-gh** [comment]
Thanks for replying, I will take a look at it.
but because I'm a senior high student in China mainland, it's hard for me to do that until the 30th day of this month
sorry

**Comment by XIAYM-gh** [comment]
So, I've implemented 4 handling methods in my PR and here are them:
 - `THROW_EXCEPTION`, it's the original way to handle duplicate keys
 - `OVERWRITE` and `IGNORE`, they are quite useful actually
 - `MERGE_INTO_ARRAY`, this is the default method that the [json-lib](https://github.com/kordamp/json-lib) use, and it may be useful sometimes for somebody

What do you think about them?

**Comment by stleary** [comment]
@XIAYM-gh Thanks for posting. 

For context, here is what [rfc-8259](https://datatracker.ietf.org/doc/html/rfc8259) says about objects:

`An object structure is represented as a pair of curly brackets
   surrounding zero or more name/value pairs (or members).  A name is a
   string.  A single colon comes after each name, separating the name
   from the value.  A single comma separates a value from a following
   name.  The names within an object SHOULD be unique.

      object = begin-object [ member *( value-separator member ) ]
               end-object

      member = string name-separator value

   An object whose names are all unique is interoperable in the sense
   that all software implementations receiving that object will agree on
   the name-value mappings.  When the names within an object are not
   unique, the behavior of software that receives such an object is
   unpredictable.  Many implementations report the last name/value pair
   only.  Other implementations report an error or fail to parse the
   object, and some implementations report all of the name/value pairs,
   including duplicates.

   JSON parsing libraries have been observed to differ as to whether or
   not they make the ordering of object members visible to calling
   software.  Implementations whose behavior does not depend on member
   ordering will be interoperable in the sense that they will not be
   affected by these differences.`

The JSON-Java object representation is fixed as an unordered map with unique keys in this 
implementation. That will not be changed, so `ignore` is not an option.
If someone has a reasonable use case for `merge_into_array`, feel free to 
post a comment, otherwise it should probably be omitted as well. 
That leaves `throw_exception` (the default behavior), and `overwrite`.

No objection if you want to try adding `overwrite` as an opt-in behavior in `JSONParserConfiguration`
or `ParserConfiguration`. It is probably not necessary to use `JsonDuplicateKeyStrategy`.

**Comment by XIAYM-gh** [comment]
Oh thanks, I will do it as soon as possible
